"""
Decimate over-tessellated OWI-535 OBJ meshes in-place.

Background
----------
The OWI-535 meshes under
  ``robot-renderer/src/robot_renderer/robots/owi535/*.obj``
were generated by a DAE-to-OBJ conversion that never ran any simplification.
The result is absurdly dense for rendering purposes:

    74 OBJ files
    total faces   : ~235 000
    largest mesh  : ~122 000 faces (single file)

PyTorch3D's coarse rasterizer then overflows ``max_faces_per_bin`` on the
largest mesh, and bumping that limit is not a real fix because GPU memory
for the bin buffer scales with it (you hit OOM before you cover 122k).
Simplification is therefore required, but an arbitrary 2k to 5k cap is not a
fidelity guarantee. The asset pipeline preserves substantially more geometry
in the two difficult parts (see the targets in the manifest).

What this tool does
-------------------
For every ``*.obj`` in the OWI-535 mesh folder, if its face count exceeds
``--max-faces-per-mesh``, the tool decimates to that target using
Quadric Edge-Collapse (Open3D backend, falls back to ``fast_simplification``
if Open3D's simplifier is unavailable) and rewrites the file in place.

The OBJ header (``mtllib`` + ``usemtl`` + any comments) is preserved
verbatim, so the per-mesh material assignments remain intact.  A ``.orig``
backup is written alongside the first time the tool runs (unless
``--no-backup`` is given).

Note: for a checkout without the OWI meshes, ``tools/fetch_assets.py`` is the
canonical path: it downloads the originals and decimates via meshoptimizer
(reusing this module's OBJ I/O).  This standalone tool remains for re-decimating
an existing mesh set to a different face budget; its outputs are experimental,
not the reference assets used by the renderer.

Usage (from repo root)
----------------------
    # Default: decimate any OBJ with >5000 faces down to 5000.
    python tools/decimate_owi535_meshes.py

    # Preview, don't touch files.
    python tools/decimate_owi535_meshes.py --dry-run

    # More aggressive cap.
    python tools/decimate_owi535_meshes.py --max-faces-per-mesh 2000

    # Restore from .orig backups.
    python tools/decimate_owi535_meshes.py --restore

Requirements
------------
One of the following (pick whichever is easier to install):
    pip install open3d
    pip install fast-simplification numpy
"""
from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
MESH_DIR = REPO_ROOT / "src/robot_renderer/robots/owi535"
BACKUP_SUFFIX = ".orig"


# ---------------------------------------------------------------------------
# OBJ I/O: single-material, no UVs / normals (matches the OWI-535 format).
# ---------------------------------------------------------------------------


@dataclass
class ObjData:
    header: List[str]                   # comments + mtllib + usemtl, verbatim
    verts: np.ndarray                   # (N, 3) float64
    faces: np.ndarray                   # (M, 3) int64, 0-indexed


def _read_obj(path: Path) -> ObjData:
    header: List[str] = []
    verts: List[Tuple[float, float, float]] = []
    faces: List[Tuple[int, int, int]] = []

    with path.open("r") as fh:
        for line in fh:
            stripped = line.strip()
            if not stripped:
                # Preserve one leading blank-ish line position only if in header.
                if not verts:
                    header.append(line.rstrip("\n"))
                continue
            if stripped.startswith(("#", "mtllib", "usemtl", "o ", "g ")):
                header.append(stripped)
                continue
            if stripped.startswith("v "):
                parts = stripped.split()
                verts.append((float(parts[1]), float(parts[2]), float(parts[3])))
                continue
            if stripped.startswith("f "):
                parts = stripped.split()[1:]
                # Handle "v", "v/vt", "v/vt/vn", "v//vn" uniformly by taking the first int.
                idx = [int(p.split("/")[0]) - 1 for p in parts]
                if len(idx) == 3:
                    faces.append((idx[0], idx[1], idx[2]))
                elif len(idx) > 3:
                    # Triangulate an n-gon as a fan.
                    for k in range(1, len(idx) - 1):
                        faces.append((idx[0], idx[k], idx[k + 1]))
                continue
            # vt / vn / s / anything else is dropped silently (OWI meshes don't use them).

    return ObjData(
        header=header,
        verts=np.asarray(verts, dtype=np.float64),
        faces=np.asarray(faces, dtype=np.int64),
    )


def _write_obj(path: Path, data: ObjData) -> None:
    with path.open("w") as fh:
        for h in data.header:
            fh.write(h + "\n")
        for v in data.verts:
            fh.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for f in data.faces:
            # OBJ is 1-indexed.
            fh.write(f"f {f[0] + 1} {f[1] + 1} {f[2] + 1}\n")


# ---------------------------------------------------------------------------
# Decimation backends: try Open3D first, then fast_simplification.
# ---------------------------------------------------------------------------


def _decimate_open3d(verts: np.ndarray, faces: np.ndarray, target_faces: int):
    import open3d as o3d  # type: ignore[import-not-found]
    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.triangles = o3d.utility.Vector3iVector(faces)
    mesh.remove_duplicated_vertices()
    mesh.remove_duplicated_triangles()
    mesh.remove_degenerate_triangles()
    simplified = mesh.simplify_quadric_decimation(target_faces)
    return (
        np.asarray(simplified.vertices, dtype=np.float64),
        np.asarray(simplified.triangles, dtype=np.int64),
    )


def _decimate_fast_simplification(verts: np.ndarray, faces: np.ndarray, target_faces: int):
    import fast_simplification  # type: ignore[import-not-found]
    target_ratio = min(1.0, target_faces / max(faces.shape[0], 1))
    new_v, new_f = fast_simplification.simplify(
        verts.astype(np.float32),
        faces.astype(np.int32),
        target_reduction=1.0 - target_ratio,
    )
    return np.asarray(new_v, dtype=np.float64), np.asarray(new_f, dtype=np.int64)


def _decimate(verts: np.ndarray, faces: np.ndarray, target_faces: int):
    try:
        return _decimate_open3d(verts, faces, target_faces)
    except ImportError:
        pass
    except Exception as e:  # open3d installed but simplifier failed; fall through
        print(f"  open3d decimator error ({e}); trying fast_simplification...",
              file=sys.stderr)
    try:
        return _decimate_fast_simplification(verts, faces, target_faces)
    except ImportError:
        raise RuntimeError(
            "Neither open3d nor fast-simplification is installed.\n"
            "Install one:  pip install open3d   (or)   pip install fast-simplification"
        ) from None


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _iter_obj_files() -> List[Path]:
    return sorted(MESH_DIR.glob("*.obj"))


def _restore_backups() -> None:
    restored = 0
    for obj in _iter_obj_files():
        bak = obj.with_suffix(obj.suffix + BACKUP_SUFFIX)
        if bak.exists():
            shutil.copy2(bak, obj)
            restored += 1
    print(f"Restored {restored} file(s) from {BACKUP_SUFFIX} backups.")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--max-faces-per-mesh", type=int, default=5000,
                        help="Target face count per mesh after decimation "
                             "(meshes already under this are left alone). "
                             "Default: 5000.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Only print what would change, don't write anything.")
    parser.add_argument("--no-backup", action="store_true",
                        help=f"Don't create '*{BACKUP_SUFFIX}' backup files.")
    parser.add_argument("--restore", action="store_true",
                        help=f"Restore every .obj from its '*{BACKUP_SUFFIX}' backup and exit.")
    args = parser.parse_args(argv)

    if args.restore:
        _restore_backups()
        return 0

    if not MESH_DIR.is_dir():
        print(f"ERROR: mesh dir not found: {MESH_DIR}", file=sys.stderr)
        return 1

    target = args.max_faces_per_mesh
    files = _iter_obj_files()
    print(f"Scanning {len(files)} OBJ files in {MESH_DIR.relative_to(REPO_ROOT)}")
    print(f"Target faces per mesh: {target}  (dry_run={args.dry_run})\n")

    touched = 0
    total_before = total_after = 0

    for obj in files:
        data = _read_obj(obj)
        n_before = data.faces.shape[0]
        total_before += n_before

        if n_before <= target:
            total_after += n_before
            continue

        print(f"[{obj.name}] {n_before} faces; decimating to at most {target}...")
        new_v, new_f = _decimate(data.verts, data.faces, target)
        n_after = new_f.shape[0]
        total_after += n_after
        print(f"    done: verts {data.verts.shape[0]} to {new_v.shape[0]}, "
              f"faces {n_before} to {n_after}")

        if args.dry_run:
            continue

        if not args.no_backup:
            bak = obj.with_suffix(obj.suffix + BACKUP_SUFFIX)
            if not bak.exists():
                shutil.copy2(obj, bak)

        _write_obj(obj, ObjData(header=data.header, verts=new_v, faces=new_f))
        touched += 1

    print("\n--- summary ---")
    print(f"files scanned     : {len(files)}")
    print(f"files touched     : {touched}{' (dry-run; no files modified)' if args.dry_run else ''}")
    print(f"total faces before: {total_before}")
    print(f"total faces after : {total_after}")
    print(f"reduction         : {100.0 * (1 - total_after / max(total_before, 1)):.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
